version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - ./database/table.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  web:
    image: node:14-alpine
    depends_on:
      - db
    working_dir: /app
    command: npm run start:dev
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
  admin:
    image: node:14
    restart: always
    working_dir: /app
    command: npm run start:admin
    volumes:
      - ./:/app
    ports:
      - "1234:1234"
